# Generated by Django 4.2.4 on 2023-08-27 12:23

import app_hm10.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=350)),
                ("path", models.ImageField(upload_to=app_hm10.models.update_filename)),
            ],
        ),
    ]
